baseURL = "https://prabhujayakumar.dev"
languageCode = "en-us"
title = "Prabhu Jayakumar"
theme = "beautifulhugo"
googleAnalytics = "UA-162983984-1"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "prabhujayakumar"

[Params]
  subtitle = "Developer | Devops Engineer | SRE"
  mainSections = ["blog"]
  # logo = "img/my-dp.png" # Expecting square dimensions
  # favicon = "img/my-dp.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  showApplauseButton = true


[Author]
  name = "Prabhu Jayakumar"
  email = "j.prabhu91@gmail.com"
  github = "prabhu43"
  linkedin = "prabhujayakumar"
  website = "https://www.thoughtworks.com/profiles/prabhu-jayakumar"

[[menu.main]]
    name = "me"
    weight = 20 #The larger the weight, the more on the right this item will be
    url = "/me" #URL address
[[menu.main]]
    name = "Blog"
    weight = 10
    url = "/"
